[build]
  command = "npm install && pip install -r requirements.txt"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.10"
